import Config

# Configure your database
config :aimailbox, Aimailbox.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "aimailbox_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :aimailbox, AimailboxWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "Ho7Tl2K8Ifu4fjj87TscOPZRuKQ/Ds/eQBiPEdE1LC33/vbSSw6GUVRYs3b2dJuD",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:aimailbox, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:aimailbox, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :aimailbox, AimailboxWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/aimailbox_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :aimailbox, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Configure Google OAuth
# IMPORTANT: Copy .env.example to .env and add your credentials
# Get credentials from: https://console.cloud.google.com/apis/credentials
config :ueberauth, Ueberauth.Strategy.Google.OAuth,
  client_id: System.get_env("GOOGLE_CLIENT_ID") || raise("GOOGLE_CLIENT_ID not set"),
  client_secret: System.get_env("GOOGLE_CLIENT_SECRET") || raise("GOOGLE_CLIENT_SECRET not set")

# Configure encryption key
# IMPORTANT: Set CLOAK_KEY in your .env file
# Generate with: echo -n $(mix phx.gen.secret 32) | base64
cloak_key = System.get_env("CLOAK_KEY") || raise("CLOAK_KEY not set")

config :aimailbox, Aimailbox.Encrypted,
  ciphers: [
    default: {Cloak.Ciphers.AES.GCM, tag: "AES.GCM.V1", key: Base.decode64!(cloak_key)}
  ]

# OpenAI API Key
# IMPORTANT: Set OPENAI_API_KEY in your .env file
# Get from: https://platform.openai.com/api-keys
config :aimailbox, :openai_api_key,
  System.get_env("OPENAI_API_KEY") || raise("OPENAI_API_KEY not set")
